---
- name: life's purpose
  hosts: "{{host}}"
  gather_facts: 'no'


    
  tasks:

    - name: Reboot {{host}}
      block: 

      - name: Reboot msg {{host}}
        ansible.builtin.debug:
          msg: System reboot
      # - name: test command 
      #   ansible.builtin.command: "ls"
      - name: "Reboot action: {{host}}"
        # ansible.builtin.reboot:
        #   reboot_command: /usr/sbin/reboot
        #   reboot_timeout: 3600
        # ansible.builtin.shell: "sleep 30; /usr/sbin/reboot"
        ansible.builtin.shell: "sleep 30; shutdown -r +1"
        async: 1
        poll: 0
        become: true
        become_user: root      
      when: act == 'reboot'
      
    
    - name: Shutdown {{host}} 
      block:
      - name: Shutdown msg {{host}}
        ansible.builtin.debug:
          msg: System shut
      # - name: test command 
      #   ansible.builtin.command: "ls"
        
      
      - name: "Shutdown action: {{host}}"
        # ansible.builtin.reboot:
        #   delay: 30
        ansible.builtin.shell: "sleep 30; /usr/sbin/shutdown +1"
        async: 1
        poll: 0
        become: true
        become_user: root    
      when: act == 'shut'

    - name: Wait for the {{ act }} to complete
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
      when: (act == 'shut') or (act == 'reboot')
