---
- name: certified purpose
  hosts: "{{host}}"
  gather_facts: 'no'

  # collections:
  #   community.general.mail
  tasks:
    - name: certified update
      shell: 'certbot renew'
      register: cert_out
      become: true
      become_method: su
      become_flags: '-s /bin/sh'

    - name: Sending an e-mail using SMTP servers
      community.general.mail:
        host: '{{ mail_host }}'
        port: 587
        sender: me
        username: me
        password: '{{ passwdd }}'
        to: '{{ to_v }}'
        subject: Ansible-report
        body: 'Out: {{ cert_out.stderr_lines }}' 
        secure: starttls
      delegate_to: localhost
      when: cert_out.changed
