---
- name: certified purpose
  hosts: "{{host}}"
  gather_facts: 'no'

  collections:
    community.general.mail
  tasks:
    - name: certified update
      shell: 'echo certbot renew'
      register: cert_out

    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: centos.jeromeothompson.com
        port: 587
        username: root
        to: Me <me@jeromeothompson.com>
        subject: Ansible-report
        body: 'Out: {{ cert_out }}' 
