---
- name: certified purpose
  hosts: "{{host}}"
  gather_facts: 'no'

  collections:
    - community.general
    
  tasks:
    - name: certified update
      shell: 'certbot renew'
      register: cert_out
      become: true
      become_method: su
      become_flags: '-s /bin/sh'

    - name: Sending an e-mail using SMTP servers
      community.general.mail:
      #mail2:
        host: '{{ mail_host }}'
        port: '{{ port }}'
        sender: '{{ sender }}'
        username: '{{ username }}'
        password: '{{ passwdd }}'
        to: '{{ to_v }}'
        subject: Ansible-report
        body: 'Out: {{ cert_out.stderr_lines }}' 
        secure: starttls
      #no_log: true
      delegate_to: localhost
      when: cert_out.changed
