---
# - name: Environment
#   hosts: localhost
#   connection: local
#   gather_facts: False


#   # environment:
#   #   OPENSSL_CONF: /var/tmp/openssl.cnf

#   tasks:
#     - name: customize /etc/environment
#       ansible.builtin.lineinfile:
#         dest: "/etc/environment"
#         state: present
#         regexp: "^OPENSSL_CONF="
#         line: "OPENSSL_CONF=/var/tmp/openssl.cnf"

# https://docs.joshuatz.com/random/tp-link-kasa/
# https://www.uuidgenerator.net/version4
# https://www.tp-link.com/jp/support/faq/3542/
# https://github.com/seemong/py-tplink-cloud-api/tree/master
# https://python-kasa.readthedocs.io/en/latest/cli.html#provisioning


- name: "Renewed purpose"
  # hosts: localhost
  hosts: '{{ host }}'
  gather_facts: false
  # become: true


  vars:
    path_list:
      - { remote: '/mnt/user/nfs', local: '/mnt/nfs11', cld: '/DataVolume/shares/Bump' }
      - { remote: '/mnt/user/vmdata', local: '/mnt/vmdata11', cld: '/DataVolume/shares/dtad' }
      - { remote: '/mnt/user/tmpshr', local: '/mnt/tmpshr11', cld: '/DataVolume/shares/pihad' }

  tasks:
    - name: Install python package
      ansible.builtin.pip:
        name: '{{ item }}'
      loop:
        - argparse
        - certifi
        # - json
        # - pdb
        # - pprint
        # - ssl
        # - sys
        # - time
        - typing 
        - urllib3
      delegate_to: localhost

    - name: execute turn on dev script
      # ansible.builtin.script:
      shell: python library/tplink_cloud_api.py turnonchild --username='{{ usernm }}' --password="{{ passwd }}" --device="{{ dev }}" --child="{{ child }}" --tid="{{ tid }}"
        # chdir: /tmp
      delegate_to: localhost

    - name: Wait 1440 seconds, but only start checking after 720 seconds
      ansible.builtin.wait_for_connection:
        delay: 720
        timeout: 1440


    - name: Add mnt folder locations 
      ansible.builtin.file:
        path: "{{ item.local }}"
        state: directory
        # owner: foo
        # group: foo
        mode: '0755'
      loop: '{{ path_list }}'


    - name: Mount NFS volumes
      ansible.posix.mount:
        src: "{{ nfs_srv }}:{{ item.remote }}"
        path: "{{ item.local }}"
        opts: nfsvers=3,rw,relatime,user
        state: mounted
        fstype: nfs
      loop: '{{ path_list }}'
      tags: mount


    - name: Add cld folder locations 
      ansible.builtin.file:
        path: "{{ item.cld }}"
        state: directory
        # owner: foo
        # group: foo
        # mode: '0755'
      loop: '{{ path_list }}'

    - name: Synchronization using rsync protocol on cld
      shell: rsync --ignore-existing -avhrt  "{{ item.local }}/" "{{ item.cld }}/"
      # ansible.posix.synchronize:
      #   src: "{{ item.local }}/"
      #   # dest: rsync:"{{ mycld }}/{{ item.cld }}/"
      #   dest: "{{ item.cld }}/"
      # delegate_to: localhost
      loop: '{{ path_list }}'
      # delegate_to: "{{ host }}"
      ignore_errors: yes 
      when: todo is undefined


    - name: Unmount nfs mounted volumes
      ansible.posix.mount:
        path: "{{ item.local }}"
        state: unmounted
      loop: '{{ path_list }}'
      tags: umount

    - name: Remove nfs locations created
      ansible.builtin.file:
        path: "{{ item.local }}"
        # owner: foo
        # group: foo
        state: "absent"
        # mode: '0755'
      loop: '{{ path_list }}'

    - name: Pause for 60 seconds before shutdown
      ansible.builtin.pause:
        seconds: 60

    - name: Shutdown device
      shell:  /sbin/shutdown -h -P now

    - name: Pause for 2 minutes to allow for shutdown
      ansible.builtin.pause:
        minutes: 2

    - name: execute turn off dev script
      # ansible.builtin.script:
      shell: python library/tplink_cloud_api.py turnoffchild --username='{{ usernm }}' --password="{{ passwd }}" --device="{{ dev }}" --child="{{ child }}" --tid="{{ tid }}"
        # chdir: /tmp
      delegate_to: localhost
