---
# https://stackoverflow.com/questions/72403652/lookup-disk-device-elements-in-libvirt-xml-with-ansible
- name: "Unknown purpose"
  hosts: localhost
  gather_facts: false

  vars:
    # uuid_disk1: { id: '', target: 'sda', src: '', type: 'unk', size : '9.1T', cont: 1}                                          # VCJUJZYP
    uuid_disk1: { id: 'cf851fbc-ad26-4cb3-869a-69bef61fabef', target: 'sda', src: '', type: 'xfs', size : '9.1T', cont: 1}                                          # VCJUJZYP
    uuid_disk2: { id: 'f1f01cf8-ba74-4d84-891f-bfcec4fd7f26', target: 'sdb', src: '', type: 'xfs', size: '9.1T', cont: 0}       # VHGEH9XM
    uuid_disk3: { id: 'b7b7c699-eda8-4729-9552-5e78a043fd24', target: 'sdc', src: '', type: 'xfs', size: '9.1T', cont: 2}       # VHG5VZBM
    uuid_disk4: { id: '767519c2-ffe2-40c4-b7fe-5fa432eb5aab', target: 'sdd', src: '', type: 'btrfs', size: '476.9G',cont: 3}    # KA22419110A0518
    uuid_disk5: { id: '44fe44ea-a64e-4ea8-aa0f-9b4a9b506060', target: 'sde', src: '', type: 'btrfs', size: '1.8T', cont: 4}     # SJD1N588911901T4D
    uuid_disk6: { id: '360cab21-63a3-4edd-b784-a504d194462b', target: 'sdf', src: '', type: 'btrfs', size: '931.5G', cont: 5}   # ASA5M000111005C12
    file_loc: 'library/virt_update.xml'
    endplayStr: 'ENDPLAY'

  tasks:
    - name: Print lsblk out
      ansible.builtin.command: lsblk -o NAME,SIZE,FSTYPE,UUID
      register: lsblk_output
      changed_when: false
      tags: ['incasesowntwrong', 'incasesowntwrongXML']


    - name: Get src disk for all listed disks
      ansible.builtin.set_fact:
        disks_list: "{{ disks_list | default([]) + [(item | disk_select(lsblk_output.stdout_lines, endplayStr))] }}"
      loop:
        - '{{ uuid_disk1 | to_json | string }}'
        - '{{ uuid_disk2 | to_json | string }}'
        - '{{ uuid_disk3 | to_json | string }}'
        - '{{ uuid_disk4 | to_json | string }}'
        - '{{ uuid_disk5 | to_json | string }}'
        - '{{ uuid_disk6 | to_json | string }}'
      tags: ['incasesowntwrong', 'incasesowntwrongXML']


    - name: Halt the play if one of the disk src was not found
      ansible.builtin.meta: end_play
      when: endplayStr in (disks_list | map(attribute='src') | list)  
      tags: ['incasesowntwrong', 'incasesowntwrongXML']
        
    - name: Print a disks list
      debug:
        var:  item.src
      loop: "{{ disks_list }}"
      tags: ['incasesowntwrong', 'incasesowntwrongXML']

    

    - name: Get {{ my_vm }} VM XML configuration
      ansible.builtin.command: virsh dumpxml '{{my_vm}}'
      register: vm_xml_output
      tags: ['incasesowntwrongXML']

    - name: Print {{ my_vm }} VM XML
      ansible.builtin.debug:
        var: vm_xml_output.stdout
      tags: ['incasesowntwrongXML']


    - name: Write old {{ my_vm }} dev changes to file 
      ansible.builtin.copy:
        content: "{{ vm_xml_output.stdout }}"
        dest: '{{ file_loc }}.old'
        mode: '0644'
      tags: ['incasesowntwrongXML']

    - name: Set val with VM XML configuration
      ansible.builtin.set_fact:
        modified_output: "{{ vm_xml_output.stdout }}"
      tags: ['incasesowntwrongXML']

    - name: Replace multiple dev src disk lines in {{ my_vm }}
      ansible.builtin.set_fact:
        modified_output: "{{ modified_output | ansible.builtin.regex_replace(regexp, replacement, multiline=True) }}"
      vars:
        regexp: "<source dev='/dev/sd.'/>(\\s?)\n(\\s+)<backingStore/>(\\s?)\n(\\s+)<target dev='{{item.target}}'" 
        replacement: |-
          <source dev='/dev/{{item.src}}'/>
                <backingStore/>
                <target dev='{{item.target}}'
      loop: "{{ disks_list }}"
      tags: ['incasesowntwrongXML']


    - name: Extract version using regex_search
      ansible.builtin.set_fact:
        dev_disk_list: "{{ dev_disk_list  | default([]) + [ split_string.rsplit('</disk>')[item] + '</disk>' | default('')] }}"
      vars:
        split_string: "{{ modified_output.split('</emulator>')[1] | default('') }}"
      loop: "{{ range(disks_list | length) | list  }}"
      tags: ['incasesowntwrongXML']

    - name: Debug IT
      ansible.builtin.debug:
        msg: "{{ dev_disk_list }}"
      tags: ['incasesowntwrongXML']
        

    - name: Loop through dev list
      ansible.builtin.include_tasks: library/updatee_virt_vm.yml
      loop: "{{ dev_disk_list }}"
      loop_control:
        loop_var: item 

    - name: Start a VM
      community.libvirt.virt:
        name: '{{ my_vm }}' 
        state: running
    
