---
- name: Execute turn off dev script
  ansible.builtin.shell: |
    python library/tplink_cloud_api.py turnoffchild --username='{{ usernm }}' --password="{{ passwd }}" --device="{{ dev }}"
    --child="{{ child }}" --tid="{{ tid }}"
  # chdir: /tmp
  delegate_to: localhost
  no_log: true
  changed_when: my_output.rc != 0
  tags: py_tun_off